server:
  port: 8080

spring:
  application:
    name: finance
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        connection:
          isolation: TRANSACTION_REPEATABLE_READ
          url:       ${spring.datasource.url}
          username:  ${spring.datasource.username}
          password:  ${spring.datasource.password}
          autocommit: false
          driver_class: ${spring.datasource.driver-class-name}
        transaction:
          jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
          coordinator_class: jdbc
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: never

jwt:
  secret: y7K8s0Pq2X9Rv4HdU5Jm1Zt3Wq6Ne8B4
  expiration-ms: 3600000